name: 'Release Extension'

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Use JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install and Build
      run: |
        npm install
        npm run compile
    - name: Publish to Open VSX Registry
      continue-on-error: true
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.OPEN_VSC_PUBLISH_TOKEN }}
    - name: Publish to Visual Studio Marketplace
      continue-on-error: true
      uses: HaaLeo/publish-vscode-extension@v0
      with:
        pat: ${{ secrets.VSC_PUBLISH_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
